development:
  dialect: postgres
  database: gobuff_realworld_example_app_development
  user: postgres
  password: postgres
  host: {{envOr "DATABASE_HOST" "127.0.0.1"}}
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/gobuff_realworld_example_app_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/gobuff_realworld_example_app_production?sslmode=disable"}}
